### ISSUE TITLE
phpunit.xml e estrutura de testes

### ISSUE THREAD

**Issue by marabesi** [hagnat/cnab#7]
A pasta de testes está com seguinte estrutura

teste
  |___ phpunit.xml

E provavelmente iremos ter as suites de testes dentro da pasta teste, ficando:
```
teste
  |___ phpunit.xml
          ClasseTeste1.php
          ClasseTeste2.php
          Pasta1
              |___ ClasseTeste3.php
                      ClasseTeste3.php
```

Agora vem a pergunta, não deveriamos extrair o arquivo phpunit.xml para fora da pasta **teste** para executarmos a suite a partir do diretório raiz ?

```
phpunit.xml
src
teste
  |___
          ClasseTeste1.php
          ClasseTeste2.php
          Pasta1
              |___ ClasseTeste3.php
                      ClasseTeste3.php
```

**Comment by marabesi** [comment]
@hagnat

**Comment by hagnat** [comment]
- logicamente pensando, o arquivo ```phpunit.xml``` é um arquivo de testes e deveria, portanto, estar contido na pasta de testes
- se tu verificar a implementação do ```composer.json``` no pull request #6, vai verificar que eu criei um comando para lançar o phpunit a partir do composer, com toda parametrização já definida
  - para executar os testes unitarios, bastará executar ```composer test:unit```

**Comment by hagnat** [comment]
ademais, a estrutura de diretorios que serguirei será
```
src/
  Application/
  Domain/
  Infrastructure/
tests/
  functional/
    Infrastructure/
  unit/
    Application/
    Domain/
  phpunit.xml
